import type { Theme, ThemeId } from "./types";

/**
 * Los únicos 4 presets del sistema (aprobados en la propuesta de Frontend
 * System v1). Deliberadamente pocos y curados — el admin elige un id, nunca
 * escribe colores ni CSS (ver BrandOverride para el único ajuste permitido).
 */
export const THEME_PRESETS: Record<ThemeId, Theme> = {
  "premium-light": {
    id: "premium-light",
    name: "Premium Light",
    colors: {
      background: "#F7F6F2",
      surface: "#FFFFFF",
      surfaceMuted: "#F0EEE7",
      foreground: "#14161A",
      foregroundMuted: "#5B5A52",
      primary: "#0B5D52",
      primaryForeground: "#FFFFFF",
      secondary: "#14161A",
      secondaryForeground: "#FFFFFF",
      accent: "#C9A24B",
      accentForeground: "#14161A",
      destructive: "#B3261E",
      destructiveForeground: "#FFFFFF",
      success: "#1F6B3C",
      successForeground: "#FFFFFF",
      warning: "#8A5A00",
      warningForeground: "#FFFFFF",
      border: "#DEDCD2",
      focusRing: "#0B5D52",
    },
    fontPreset: "serif-display",
    radiusPreset: "soft",
    buttonPreset: "solid",
    cardPreset: "flat-border",
    sectionSpacingPreset: "comfortable",
  },
  "premium-dark": {
    id: "premium-dark",
    name: "Premium Dark",
    colors: {
      background: "#15140F",
      surface: "#1D1B14",
      surfaceMuted: "#242018",
      foreground: "#F3EFE6",
      foregroundMuted: "#A9A493",
      primary: "#C9A24B",
      primaryForeground: "#15140F",
      secondary: "#F3EFE6",
      secondaryForeground: "#15140F",
      accent: "#0B5D52",
      accentForeground: "#F3EFE6",
      destructive: "#E5766D",
      destructiveForeground: "#15140F",
      success: "#7FBE95",
      successForeground: "#15140F",
      warning: "#E0B559",
      warningForeground: "#15140F",
      border: "#3A362C",
      focusRing: "#C9A24B",
    },
    fontPreset: "serif-display",
    radiusPreset: "soft",
    buttonPreset: "solid",
    cardPreset: "soft-shadow",
    sectionSpacingPreset: "comfortable",
  },
  editorial: {
    id: "editorial",
    name: "Editorial",
    colors: {
      background: "#FFFFFF",
      surface: "#FAFAF8",
      surfaceMuted: "#F1F0EB",
      foreground: "#161514",
      foregroundMuted: "#4A4842",
      primary: "#7A2E2E",
      primaryForeground: "#FFFFFF",
      secondary: "#161514",
      secondaryForeground: "#FFFFFF",
      accent: "#161514",
      accentForeground: "#FFFFFF",
      destructive: "#7A2E2E",
      destructiveForeground: "#FFFFFF",
      success: "#2E5B3E",
      successForeground: "#FFFFFF",
      warning: "#7A5A2E",
      warningForeground: "#FFFFFF",
      border: "#E7E5DD",
      focusRing: "#7A2E2E",
    },
    fontPreset: "editorial-serif",
    radiusPreset: "sharp",
    buttonPreset: "outline-accent",
    cardPreset: "editorial-divider",
    sectionSpacingPreset: "spacious",
  },
  "high-conversion": {
    id: "high-conversion",
    name: "High Conversion",
    colors: {
      background: "#FCFBF9",
      surface: "#FFFFFF",
      surfaceMuted: "#F2F1EC",
      foreground: "#14161A",
      foregroundMuted: "#5B5A52",
      primary: "#E1502A",
      primaryForeground: "#FFFFFF",
      secondary: "#1B2A4A",
      secondaryForeground: "#FFFFFF",
      accent: "#1B2A4A",
      accentForeground: "#FFFFFF",
      destructive: "#B3261E",
      destructiveForeground: "#FFFFFF",
      success: "#1F6B3C",
      successForeground: "#FFFFFF",
      warning: "#8A5A00",
      warningForeground: "#FFFFFF",
      border: "#E7E5DD",
      focusRing: "#E1502A",
    },
    fontPreset: "sans",
    radiusPreset: "round",
    buttonPreset: "pill",
    cardPreset: "soft-shadow",
    sectionSpacingPreset: "compact",
  },
};

export function getTheme(id: ThemeId): Theme {
  return THEME_PRESETS[id];
}
